### PR TITLE
[#127260745] Rep release - initial version

### PR DESCRIPTION
**Pull request by combor**
## What

This PR brings initial version of REP via bosh-release that was compiled against patched version of locket library and fixed https://github.com/cloudfoundry/diego-release/issues/177 issue. Locket patch has been provided by [forking upstrem repo](https://github.com/alphagov/paas-locket) , cherry-picking [fix commit](https://github.com/cloudfoundry/locket/commit/9859166ea0fe5cb67c48eb5ecc36d3099d3be0da) to the branch based on diego release 0.1476.0 and replacing locket submodule in /src directory of this release. 

## How to review

- hijack bosh container 
- `git clone git@github.com:alphagov/paas-rep-boshrelease.git`
- `git checkout 127260745_rep_release`
- `bosh create release --force --name rep`
- `bosh upload release`
- now you can test it with https://github.com/alphagov/paas-cf/pull/395
- after merging put 0.0.1 tag on master 

## Who can review 

not @keymon or @combor

### CODE REVIEW

**Comment by mtekel** [comment]
The significant changes here are:
1. this is a standalone rep relase
2. it uses our own version of locket

It would be nice if 1. was just extraction and 2. was done as a separate commit, currently it's lost in 2b583c7b8cb7423742a62fc22a596645cbd822be

**Comment by combor** [comment]
@mtekel 

Not sure what do you mean by "1. was just extraction". When it comes to 2 I somehow lost info about this in commit message. I'll bring it back.

**Comment by mtekel** [comment]
1. should be the 4 commits that you have there. They just extract the job, without modifying the library.
2. then on top of that add a commit that is pointing the library submodule to our fork & describe what & why in commit message

**Comment by mtekel** [comment]
works. I have downgraded collectd to 0.3 and deployed. Cells did not lose presence while consuls were being updated. I have then manually stopped consuls and intentionally broken cluster. It took a bit more than 5 seconds before rep started reporting issues

**Pull request merged**
